import { describe, it, expect, beforeEach, jest } from '@jest/globals';
import { Readable } from 'node:stream';
import { RENDER_VERSION, pictureOf, pictureOfJob } from '../src/jobPicture';
import type { PictureShelf } from '../src/jobPicture';
import type { Log } from '../src/log';

const PNG = [0x89, 0x50, 0x4e, 0x47];
const JPG = [0xff, 0xd8, 0xff];

function embedded(format: string, size: string, bytes: number[]): string[] {
  const tag = format === '' ? 'thumbnail' : `thumbnail_${format}`;
  const base64 = Buffer.from(bytes).toString('base64');

  return [`; ${tag} begin ${size} ${base64.length}`, `; ${base64.slice(0, 4)}`, `; ${base64.slice(4)}`, `; ${tag} end`, ';'];
}

const gcode = (lines: string[]): Readable => Readable.from(lines.map((line) => `${line}\n`));

describe('the picture of a job', () => {
  describe('when the slicer embedded one', () => {
    // Largest by AREA: the widest of these is the smallest of them.
    it('is the largest PNG, exactly as it was written', async () => {
      const picture = await pictureOf(
        gcode([
          ...embedded('', '480x60', [...PNG, 1]),
          ...embedded('', '300x300', [...PNG, 2]),
          ...embedded('', '220x124', [...PNG, 3]),
          'G1 X1',
        ]),
      );

      expect(picture).toEqual({ contentType: 'image/png', bytes: Buffer.from([...PNG, 2]), rendered: false });
    });

    it('is a JPG when that is what it embedded', async () => {
      const picture = await pictureOf(gcode([...embedded('JPG', '300x200', [...JPG, 7]), 'G1 X1']));

      expect(picture).toEqual({ contentType: 'image/jpeg', bytes: Buffer.from([...JPG, 7]), rendered: false });
    });

    it('passes over a QOI, however large, which a browser cannot show', async () => {
      const picture = await pictureOf(
        gcode([...embedded('', '16x16', [...PNG, 1]), ...embedded('QOI', '480x240', [0x71, 0x6f, 0x69, 0x66]), 'G1 X1']),
      );

      expect(picture.bytes).toEqual(Buffer.from([...PNG, 1]));
    });

    it('passes over a block that is not what its header says it is', async () => {
      const picture = await pictureOf(gcode([...embedded('', '380x285', [...JPG, 1]), 'G1 X1']));

      expect(picture.rendered).toBe(true);
    });

    it('reads no further than the head of the file', async () => {
      let movesPulled = 0;
      async function* aLongPlate(): AsyncGenerator<string> {
        for (const line of embedded('', '16x16', [...PNG, 1])) yield `${line}\n`;
        for (; movesPulled < 100_000; movesPulled++) yield 'G1 X1 E1\n';
      }

      const picture = await pictureOf(Readable.from(aLongPlate()));

      expect(picture.rendered).toBe(false);
      expect(movesPulled).toBeLessThan(1000);
    });

    it('is found in a plate that is nothing but its head', async () => {
      const picture = await pictureOf(gcode(embedded('', '16x16', [...PNG, 1])));

      expect(picture.rendered).toBe(false);
    });

    it('does not take one embedded after the moves have begun', async () => {
      const picture = await pictureOf(gcode(['G1 X1', ...embedded('', '16x16', [...PNG, 1])]));

      expect(picture.rendered).toBe(true);
    });
  });

  it('is a render of the plastic its moves lay when nothing was embedded', async () => {
    const picture = await pictureOf(gcode(['; generated by something', 'G1 X10 E1', 'G1 X20 E2']));

    expect(picture).toMatchObject({ contentType: 'image/png', rendered: true });
    expect(picture.bytes.readUInt32BE(16)).toBe(600);
  });

  it('lets go of the gcode once it has a picture, though there is more of it', async () => {
    const stream = Readable.from(
      (function* (): Generator<string> {
        for (const line of embedded('', '16x16', [...PNG, 1])) yield `${line}\n`;
        for (;;) yield 'G1 X1 E1\n';
      })(),
    );

    await pictureOf(stream);

    expect(stream.destroyed).toBe(true);
  });
});

describe('the picture of a job the shop holds', () => {
  const mockGcodeStream = jest.fn<PictureShelf['gcodeStream']>();
  const mockKeptPicture = jest.fn<PictureShelf['keptPicture']>();
  const mockKeepPicture = jest.fn<PictureShelf['keepPicture']>();
  const mockError = jest.fn<Log['error']>();
  const shelf: PictureShelf = { gcodeStream: mockGcodeStream, keptPicture: mockKeptPicture, keepPicture: mockKeepPicture };
  const log: Log = { info: jest.fn<Log['info']>(), error: mockError };

  const kept = Buffer.from('rendered before');
  const moves = ['M83', 'G1 X10 E1'];

  beforeEach(() => {
    mockGcodeStream.mockReset();
    mockKeptPicture.mockReset();
    mockKeepPicture.mockReset();
    mockError.mockReset();

    mockKeptPicture.mockResolvedValue(undefined);
    mockKeepPicture.mockResolvedValue(undefined);
    mockGcodeStream.mockImplementation(() => Promise.resolve(gcode(moves)));
  });

  it('is the render kept for it, without reading its gcode again', async () => {
    mockKeptPicture.mockResolvedValue(kept);

    expect(await pictureOfJob(shelf, 7, log)).toEqual({ contentType: 'image/png', bytes: kept, rendered: true });
    expect(mockKeptPicture).toHaveBeenCalledWith(7, RENDER_VERSION);
    expect(mockGcodeStream).not.toHaveBeenCalled();
  });

  it('is rendered and kept when none was', async () => {
    const picture = await pictureOfJob(shelf, 7, log);

    expect(picture.rendered).toBe(true);
    expect(mockKeepPicture).toHaveBeenCalledWith(7, RENDER_VERSION, picture.bytes);
  });

  it('is not kept when the slicer embedded it, since it is on disk already', async () => {
    mockGcodeStream.mockImplementation(() => Promise.resolve(gcode([...embedded('', '16x16', [...PNG, 1]), ...moves])));

    await pictureOfJob(shelf, 7, log);

    expect(mockKeepPicture).not.toHaveBeenCalled();
  });

  it('is still answered when it cannot be kept, and says so', async () => {
    mockKeepPicture.mockRejectedValue(new Error('the disk is full'));

    expect((await pictureOfJob(shelf, 7, log)).rendered).toBe(true);
    expect(mockError).toHaveBeenCalledWith('a rendered picture could not be kept, so it will be rendered again', {
      job: 7,
      reason: 'Error: the disk is full',
    });
  });
});
