import { describe, it, expect } from '@jest/globals';
import { READS, slicedPlate } from '../src/slicedPlate';
import type { PlateRead } from '../src/slicedPlate';

// AIDEV-NOTE: (UT) over a string, which is what the ends of a plate are by the time anything here
// sees them. That the spellings below are the ones a real plate uses is measured in
// tests/assumptions/whatAPlateSays.test.ts and cannot be answered here.
describe('what a sliced plate says about itself', () => {
  const WRITTEN_BY = '; generated by PrusaSlicer 2.9.6 on 2026-09-15 at 11:27:15 UTC';

  // Loud rather than silent: a fixture the gate turned away would otherwise read as a parser that
  // found nothing, and every assertion below would be measuring the wrong refusal.
  const readingOf = (...lines: string[]): PlateRead => {
    const plate = slicedPlate([WRITTEN_BY, ...lines].join('\n'));
    if (!plate.read) throw new Error(`this test's own plate was turned away: ${JSON.stringify(plate)}`);

    return plate;
  };

  describe('when it is a plate the shop reads', () => {
    it('names the filament the plate was sliced for', () => {
      expect(readingOf('; filament_type = PLA').filaments).toEqual(['PLA']);
    });

    it('keeps every filament named, in the order they were named', () => {
      expect(readingOf('; filament_type = PETG;PLA;ABS').filaments).toEqual(['PETG', 'PLA', 'ABS']);
    });

    it('names none when the plate says nothing about filament', () => {
      expect(readingOf('G1 X100.000 Y100.000', '; layer_height = 0.2').filaments).toEqual([]);
    });

    it('reads an estimate given in hours and minutes', () => {
      expect(readingOf('; estimated printing time (normal mode) = 2h 5m').estimatedPrintSeconds).toBe(7500);
    });

    it('reads an estimate given in days, minutes and seconds', () => {
      expect(readingOf('; estimated printing time = 1d 3m 4s').estimatedPrintSeconds).toBe(86584);
    });

    it('leaves the estimate out when what was written is not a span of time', () => {
      expect(readingOf('; estimated printing time = unknown').estimatedPrintSeconds).toBeUndefined();
    });

    it('takes the bed the plate was sliced for as the room it needs', () => {
      const room = readingOf('; bed_shape = 0x0,250x0,250x210,0x210', '; max_print_height = 220').requiredBuildVolume;

      expect(room).toEqual({ x: 250, y: 210, z: 220 });
    });

    it('says nothing about room when the plate gives a bed and no height', () => {
      expect(readingOf('; bed_shape = 0x0,250x0,250x210,0x210').requiredBuildVolume).toBeUndefined();
    });

    it('says nothing about room when the plate gives a height and no bed', () => {
      expect(readingOf('; max_print_height = 220').requiredBuildVolume).toBeUndefined();
    });

    // The head of a plate and its trailing block are handed over together, so the same setting
    // arrives twice and which one counts cannot be left to how much tail was read.
    it('keeps the first answer when a setting is written twice', () => {
      expect(readingOf('; filament_type = PLA', 'G1 X1', '; filament_type = PETG').filaments).toEqual(['PLA']);
    });

    it('reads nothing out of a line that is not a comment', () => {
      expect(readingOf('filament_type = PLA').filaments).toEqual([]);
    });
  });

  // AIDEV-NOTE: the gate, and what it is for. Reading settings out of a plate written by something
  // nobody has measured would be guessing at spellings, and a wrong guess yields a plausible volume
  // or estimate that is simply not true - which is worse than not reading one at all.
  describe('when it will not read the plate at all', () => {
    it('reads one from the version it was measured against', () => {
      expect(slicedPlate(`${WRITTEN_BY}\n; filament_type = PLA`)).toMatchObject({ read: true });
    });

    it('reads one from the oldest of that major version', () => {
      expect(slicedPlate('; generated by PrusaSlicer 2.0.0 on a day\n; filament_type = PLA')).toMatchObject({ read: true });
    });

    it('turns away a major version before the one it knows, and says what wrote it', () => {
      expect(slicedPlate('; generated by PrusaSlicer 1.41.3 on a day\n; filament_type = PLA')).toEqual({
        read: false,
        generatedBy: 'PrusaSlicer 1.41.3',
      });
    });

    // The upper bound is as deliberate as the lower: a major version nobody has seen is free to have
    // moved every spelling, and reading it anyway is the guess this exists to refuse.
    it('turns away a major version after the one it knows', () => {
      expect(slicedPlate('; generated by PrusaSlicer 3.0.0 on a day\n; filament_type = PLA')).toMatchObject({ read: false });
    });

    it('turns away another tool, and says which one it was', () => {
      expect(slicedPlate('; generated by SomeOtherSlicer 2.3.0 on a day\n; filament_type = PLA')).toEqual({
        read: false,
        generatedBy: 'SomeOtherSlicer 2.3.0',
      });
    });

    it('turns away a plate that does not say what wrote it, and has nothing to name', () => {
      expect(slicedPlate('; filament_type = PLA')).toEqual({ read: false, generatedBy: undefined });
    });

    it('says what it does read, for whoever has to write the refusal', () => {
      expect(READS).toBe('PrusaSlicer 2');
    });
  });
});
