import type { BuildVolume } from './Job.js';

/** A plate written by something the shop knows how to read, and what it says it needs. */
export interface PlateRead {
  read: true;
  /** In the order the comment named them; the first is the one that has to be loaded. */
  filaments: string[];
  estimatedPrintSeconds?: number;
  requiredBuildVolume?: BuildVolume;
}

/** A plate the shop will not read, and what it said wrote it - which is what to tell somebody. */
export interface PlateUnread {
  read: false;
  /** Exactly as the plate said it, or absent where the plate said nothing at all. */
  generatedBy?: string;
}

export type SlicedPlate = PlateRead | PlateUnread;

// AIDEV-NOTE: THE ONE PLACE A TOOL IS NAMED, and it is named on purpose. CLAUDE.md says nothing here
// may name a client, and that rule is otherwise intact - what is named here is a DIALECT of a file
// format, and the dialect has no name but the tool's because the file has no other name for itself.
// Reading settings out of a plate written by anything else would be guessing at spellings nobody has
// measured, and a wrong guess is worse than a refusal: it yields a plausible estimate or volume that
// is simply not true. So one dialect is read, every other plate is refused, and the refusal says
// what wrote it. Do not widen this without a real plate from the tool being added.
const TOOL = 'PrusaSlicer';
const OLDEST = 2;
const PAST = 3;

const DIALECT = new RegExp(`${TOOL}\\s+(\\d+)\\.(\\d+)`, 'i');

/** What the shop can read, said the way a refusal has to say it. */
export const READS = `${TOOL} ${OLDEST}`;

// The first line of a plate, and the only thing read before deciding whether to read the rest.
const GENERATED_BY = /^;\s*generated by\s+(.+?)\s+on\s/im;

// AIDEV-NOTE: every spelling here has been seen in a plate the shop actually reads. Keys belonging to
// other tools were taken out when the dialect gate went in - they had never been measured, the gate
// makes them unreachable, and a table listing them claims a support that does not exist. Adding a
// tool is a dialect above and its spellings here, together, with a real plate in tests/assumptions.
// AIDEV-NOTE: the MATERIAL and not the profile. A real plate carries `filament_settings_id` beside
// this - a quoted name for the settings somebody sliced with - and it was in here as a fallback until
// a real one was read. It is the wrong answer twice over: it is a name in the slicing tool's
// namespace rather than a material an operator loads, so a job taking it would wait for a filament
// nobody will ever say is on the machine. Refusing a plate that names no material is the better
// failure, and it says so.
const FILAMENT_KEYS = ['filament_type'];
const ESTIMATE_KEYS = ['estimated printing time (normal mode)', 'estimated printing time'];
const WIDTH_AND_DEPTH_KEYS = ['bed_shape'];
const HEIGHT_KEYS = ['max_print_height'];

// AIDEV-NOTE: `; name = value`, which is the one shape every writer of these agrees on. A line that
// is not a comment ends nothing and is simply not a setting - the block is not delimited here,
// because what this is given is already only the ends of a file.
const SETTING = /^;\s*([^=]+?)\s*=\s*(.*?)\s*$/;

/** What the comments in this much of a plate say about it, if it is a plate the shop reads at all. */
export function slicedPlate(text: string): SlicedPlate {
  const generatedBy = GENERATED_BY.exec(text)?.[1];
  if (generatedBy === undefined || !isADialectWeRead(generatedBy)) return { read: false, generatedBy };

  const said = settingsIn(text);

  return {
    read: true,
    filaments: filamentsIn(said),
    estimatedPrintSeconds: estimateIn(said),
    requiredBuildVolume: buildVolumeIn(said),
  };
}

// AIDEV-NOTE: the upper bound is as deliberate as the lower one. A major version the shop has never
// seen is free to have moved every spelling below it, and reading one on the assumption that it did
// not is the guess this gate exists to refuse. Refusing a plate somebody could have printed is the
// cheaper mistake: they are told exactly what happened and can say what the job needs by hand.
function isADialectWeRead(generatedBy: string): boolean {
  const said = DIALECT.exec(generatedBy);
  if (said === null) return false;

  const major = Number(said[1]);

  return major >= OLDEST && major < PAST;
}

function settingsIn(text: string): Map<string, string> {
  const said = new Map<string, string>();

  for (const line of text.split('\n')) {
    const match = SETTING.exec(line);
    // AIDEV-NOTE: the FIRST wins. A plate carries the same setting at the head and again in the
    // trailing block, and this is handed both ends at once - so a rule about which is needed, and
    // "the one nearest the top" is the one that does not depend on how much tail was read.
    if (match !== null && !said.has(match[1])) said.set(match[1], match[2]);
  }

  return said;
}

function firstOf(said: Map<string, string>, keys: string[]): string | undefined {
  for (const key of keys) {
    const value = said.get(key);
    if (value !== undefined && value !== '') return value;
  }

  return undefined;
}

// AIDEV-NOTE: separated by `;` where more than one is named, which collides with nothing because the
// comment marker has already been stripped by the time this sees a value. Commas are taken too, and
// cost nothing to take.
function filamentsIn(said: Map<string, string>): string[] {
  const value = firstOf(said, FILAMENT_KEYS);
  if (value === undefined) return [];

  return value
    .split(/[;,]/)
    .map((filament) => filament.trim())
    .filter((filament) => filament !== '');
}

const SPANS = /(\d+)\s*([dhms])/g;
const PER_UNIT: Record<string, number> = { d: 86400, h: 3600, m: 60, s: 1 };

// AIDEV-NOTE: `2h 5m 30s`, and every subset of it. Returned undefined rather than zero when nothing
// parses: the field is optional and absent means "this client does not know", where zero would be a
// claim that the plate takes no time and would rank its filament below everything.
function estimateIn(said: Map<string, string>): number | undefined {
  const value = firstOf(said, ESTIMATE_KEYS);
  if (value === undefined) return undefined;

  let seconds = 0;
  let found = false;
  for (const [, amount, unit] of value.matchAll(SPANS)) {
    seconds += Number(amount) * PER_UNIT[unit];
    found = true;
  }

  return found ? seconds : undefined;
}

// AIDEV-NOTE: the bed the plate was sliced FOR, which reads like an over-estimate of what the object
// needs and is the right number anyway: a plate's coordinates include the prime line, the skirt and
// the wipe tower, all placed against that bed. The object's own extent is the UNSAFE number here,
// and is deliberately not what this reads.
function buildVolumeIn(said: Map<string, string>): BuildVolume | undefined {
  const bed = firstOf(said, WIDTH_AND_DEPTH_KEYS);
  const height = firstOf(said, HEIGHT_KEYS);
  if (bed === undefined || height === undefined) return undefined;

  const corners = [...bed.matchAll(/(-?[\d.]+)\s*x\s*(-?[\d.]+)/g)].map(([, x, y]) => ({ x: Number(x), y: Number(y) }));
  const z = Number(height);
  if (corners.length === 0 || !Number.isFinite(z) || z <= 0) return undefined;

  const x = Math.max(...corners.map((corner) => corner.x));
  const y = Math.max(...corners.map((corner) => corner.y));
  if (!Number.isFinite(x) || !Number.isFinite(y) || x <= 0 || y <= 0) return undefined;

  return { x, y, z };
}
